### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by oschulz** [lejon/TSne.jl#25]
The current master branch seems to run on Julia v1.x, with a current set of dependencies, but the last release can't be installed (dependency trouble with ProgressMeter). Maybe make a new release, based on the current master, if you can find some time?

**Comment by oschulz** [comment]
CC @juliohm

**Comment by grahamas** [comment]
For future Googlers' sake, this leads to a wild goose chase of errors, beginning:

```
julia> import DifferentialEquations
[ Info: Precompiling DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
ERROR: LoadError: LoadError: UndefVarError: initialize_dae! not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at /home/graham/.julia/packages/Sundials/0yJ3G/src/common_interfa
ce/integrator_utils.jl:151
 [3] include(::Module, ::String) at ./Base.jl:377
 [4] include(::String) at /home/graham/.julia/packages/Sundials/0yJ3G/src/Sundials.jl:
3
 [5] top-level scope at /home/graham/.julia/packages/Sundials/0yJ3G/src/Sundials.jl:71
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:331 [inlined]
 [9] eval(::Expr) at ./client.jl:449
 [10] top-level scope at ./none:3
in expression starting at /home/graham/.julia/packages/Sundials/0yJ3G/src/common_inter
face/integrator_utils.jl:151
in expression starting at /home/graham/.julia/packages/Sundials/0yJ3G/src/Sundials.jl:
71
ERROR: LoadError: Failed to precompile Sundials [c3572dad-4567-51f8-b174-8c6c989267f4]
 to /home/graham/.julia/compiled/v1.4/Sundials/j8Ppj_f4Df4.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:331 [inlined]
 [9] eval(::Expr) at ./client.jl:449
 [10] top-level scope at ./none:3
in expression starting at /home/graham/.julia/packages/DifferentialEquations/xCZD1/src
/DifferentialEquations.jl:13
ERROR: Failed to precompile DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fba
a] to /home/graham/.julia/compiled/v1.4/DifferentialEquations/UQdwS_f4Df4.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
```
Diligent inspection of `Manifest.toml` reveals that `DiffEqBase` is stuck at `v6.19.0`. Explicitly adding `]add DiffEqBase@6.29.3` gives an error that `ProgressMeter` is unsatisfiable, due to `TSne`.

My solution was to remove `TSne`, but you may not be able to do that.

**Comment by oschulz** [comment]
But how does TSne depend on DiffEqBase?

**Comment by grahamas** [comment]
It doesn't, but they both depend on ProgressMeter.

Starting with `v6.20.0`, DiffEqBase, requires ConsoleProgressMonitor which requires `v1` of ProgressMeter. 

On the other hand, TSne requires ProgressMeter *less than* `v1` (implicitly, the `REQUIRE` file requires `v0.x`). 

To fix this, TSne would need to move to the `Project.toml` setup, with
```
[compat]
ProgressMeter = "1"
```

**Comment by oschulz** [comment]
Oh, yes, definitly!

**Comment by babaq** [comment]
yes, it's broken on julia 1.4, need to make a new release, or at least update on master

**Comment by submitme** [comment]
Leif, time to update this to Julia 1.4. This package was mentioned in recent Julia Computing Data Science videos, but not used since it is outdated. / Prof Villani

**Comment by PyDataBlog** [comment]
This requires urgent attention.

**Comment by juliohm** [comment]
@lejon are you still with us? Can you please share an update regarding the maintenance of this package? Would you like to give others permission to maintain if you are too busy or not interested in evolving/fixing it?

**Comment by lejon** [comment]
Hi,

Yes I'm still here. I keep thinking that I should get back to Julia coding,
because I think it is really great, but time and other prio seems to always
be against it unfortunately.

Github user @alyst has previously done a great job updating the package and
has in practice been the maintainer of late, but I guess he's also got
alot of other stuff to do. I do not think that he would mind someone else
taking over the maintainer role. Personally I'd be happy if someone wants
to take that role.

Cheers!
-Leif

On 15 Aug 2020, at 13:25, Júlio Hoffimann <notifications@github.com> wrote:

﻿

@lejon <https://github.com/lejon> are you still with us? Can you please
share an update regarding the maintenance of this package? Would you like
to give others permission to maintain if you are too busy or not interested
in evolving/fixing it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lejon/TSne.jl/issues/25#issuecomment-674385108>, or
unsubscribe

**Comment by alyst** [comment]
Sorry, I hadn't checked this package for quite a while. I've just tagged a new version that should work with current Julia and up-to-date packages.

**Comment by oschulz** [comment]
Thanks!

**Comment by oschulz** [comment]
Maybe add https://github.com/JuliaRegistries/CompatHelper.jl to the workflows, to keep the dependency version bounds up to date?

**Comment by alyst** [comment]
@oschulz That's also what I would like to do (as well as installing JuliaRegistrator app). The full setup would require adding SSH deploy key, which only the owner (@lejon) can do.
